// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1YvKNThkdFJalyUcvGicKFa9FrT0epTg',
    appId: '1:27864568819:web:e43a87d523121dee237886',
    messagingSenderId: '27864568819',
    projectId: 'fruit-hup-df9be',
    authDomain: 'fruit-hup-df9be.firebaseapp.com',
    storageBucket: 'fruit-hup-df9be.firebasestorage.app',
    measurementId: 'G-L9PNCF3HDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlJlty02DxhK7oj-InUsP-WcV-Un-u1Hg',
    appId: '1:27864568819:android:52a42d7c0fbad34e237886',
    messagingSenderId: '27864568819',
    projectId: 'fruit-hup-df9be',
    storageBucket: 'fruit-hup-df9be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA88vErfFXL9__cMtx68swTjidt4Sa04M',
    appId: '1:27864568819:ios:e8bc1936b5cb17d4237886',
    messagingSenderId: '27864568819',
    projectId: 'fruit-hup-df9be',
    storageBucket: 'fruit-hup-df9be.firebasestorage.app',
    iosBundleId: 'com.example.fruitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA88vErfFXL9__cMtx68swTjidt4Sa04M',
    appId: '1:27864568819:ios:e8bc1936b5cb17d4237886',
    messagingSenderId: '27864568819',
    projectId: 'fruit-hup-df9be',
    storageBucket: 'fruit-hup-df9be.firebasestorage.app',
    iosBundleId: 'com.example.fruitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1YvKNThkdFJalyUcvGicKFa9FrT0epTg',
    appId: '1:27864568819:web:c4983d92abcc7cce237886',
    messagingSenderId: '27864568819',
    projectId: 'fruit-hup-df9be',
    authDomain: 'fruit-hup-df9be.firebaseapp.com',
    storageBucket: 'fruit-hup-df9be.firebasestorage.app',
    measurementId: 'G-VRD3WC1NH2',
  );
}
